# Shared environment for the Duct cross toolchain. Sourced, never executed.
#
# This is LFS chapter 5: a compiler that runs on the bootstrap host but targets
# Duct, built against Duct's own glibc rather than the host's. Everything here
# is scaffolding -- none of it is packaged, and all of it is thrown away once
# the real packages have been built with it.
#
# The point of the exercise is that $DUCT_TGT is a *different* triple from the
# host's. That difference is what makes the build fail loudly if a header or a
# library leaks in from the bootstrap image, instead of silently producing
# binaries that only work by accident.

set -euo pipefail

# The staging root the toolchain targets and installs into.
DUCT=${DUCT:-/duct}

# Where sources are cached. The Dockerfile mounts a BuildKit cache here so a
# rebuild does not re-download 400 MB of tarballs.
SRC_CACHE=${DUCT_SRC_CACHE:-/srccache}

TOOLS=$DUCT/tools
BUILD_ROOT=${BUILD_ROOT:-$DUCT/build}

HOST_ARCH=$(uname -m)
case "$HOST_ARCH" in
	x86_64)  DUCT_TGT=x86_64-duct-linux-gnu;  LOADER=ld-linux-x86-64.so.2 ;;
	aarch64) DUCT_TGT=aarch64-duct-linux-gnu; LOADER=ld-linux-aarch64.so.1 ;;
	riscv64) DUCT_TGT=riscv64-duct-linux-gnu; LOADER=ld-linux-riscv64-lp64d.so.1 ;;
	*) echo "unsupported build architecture: $HOST_ARCH" >&2; exit 1 ;;
esac

export DUCT DUCT_TGT TOOLS SRC_CACHE LOADER
export PATH=$TOOLS/bin:/usr/bin:/bin
export LC_ALL=POSIX

JOBS=${DUCT_JOBS:-$(nproc 2>/dev/null || echo 4)}
export MAKEFLAGS="-j$JOBS"

log() { printf '\n=== [%s] %s\n' "${STAGE:-toolchain}" "$*" >&2; }
die() { printf '\nerror: [%s] %s\n' "${STAGE:-toolchain}" "$*" >&2; exit 1; }

# versions.env is generated by tools/pin-versions.sh and pins every upstream
# tarball to a URL and a sha256.
VERSIONS=${VERSIONS:-/duct-src/versions.env}
[ -f "$VERSIONS" ] || die "no versions.env at $VERSIONS"
# shellcheck disable=SC1090
. "$VERSIONS"

sha256_of() { sha256sum "$1" | cut -d' ' -f1; }

# These helpers report their result in a global rather than on stdout, and it is
# not a style preference. `x=$(helper)` runs the helper in a subshell, so a die()
# inside it exits only that subshell -- the caller carries on with an empty
# string, and the first symptom is a confusing error from tar three lines later.
# Setting a global keeps the failure in the caller's own shell, where `set -e`
# can actually stop it.
FETCHED=
SRC_PATH=

# Sources already fetched and verified on the host, bind-mounted read-only by
# the Dockerfile. Checking here first means a normal build downloads nothing at
# all -- which is both faster and the only way this build survives GNU's mirrors
# having a bad day, as they reliably do.
SRC_SEED=${DUCT_SRC_SEED:-/hostsrc}

# fetch_one <dest> <url> -- try the URL, then known mirrors of it.
#
# The GNU redirector returns 502 whenever a mirror behind it is unhealthy, and
# a toolchain build is far too long to lose to one flaky host. Content is
# verified by sha256 afterwards, so it does not matter which mirror answers.
fetch_one() {
	local dest=$1 url=$2 m rest urls
	urls=$url
	case "$url" in
		*ftpmirror.gnu.org/*)
			rest=${url#https://ftpmirror.gnu.org/}
			urls="$urls https://ftp.gnu.org/gnu/$rest https://mirrors.kernel.org/gnu/$rest" ;;
	esac
	for m in $urls; do
		if command -v curl >/dev/null 2>&1; then
			curl -fsSL --retry 2 --connect-timeout 20 --max-time 900 -o "$dest" "$m" >&2 && return 0
		elif command -v wget >/dev/null 2>&1; then
			wget -q -O "$dest" "$m" >&2 && return 0
		else
			die "neither curl nor wget is available"
		fi
		rm -f "$dest"
		echo "  (mirror failed: $m)" >&2
	done
	return 1
}

# fetch <VARPREFIX> -- download and verify one pinned file into $FETCHED.
fetch() {
	local prefix=$1 url sha file
	eval "url=\${${prefix}_URL:-}"
	eval "sha=\${${prefix}_SHA256:-}"
	[ -n "$url" ] || die "$prefix has no URL in versions.env"
	[ -n "$sha" ] || die "$prefix has no SHA256 in versions.env"

	file=$SRC_CACHE/$(basename "$url")
	mkdir -p "$SRC_CACHE"

	if [ ! -f "$file" ] || [ "$(sha256_of "$file")" != "$sha" ]; then
		rm -f "$file"
		local seed=$SRC_SEED/$(basename "$url")
		if [ -f "$seed" ] && [ "$(sha256_of "$seed")" = "$sha" ]; then
			cp "$seed" "$file"
		else
			fetch_one "$file.part" "$url" || die "cannot fetch $url"
			[ "$(sha256_of "$file.part")" = "$sha" ] || die "sha256 mismatch for $(basename "$url")"
			mv "$file.part" "$file"
		fi
	fi
	FETCHED=$file
}

# unpack <VARPREFIX> -- fetch and unpack into $BUILD_ROOT, setting $SRC_PATH.
unpack() {
	local prefix=$1 srcdir
	fetch "$prefix"
	eval "srcdir=\${${prefix}_SRCDIR}"
	[ -n "$srcdir" ] || die "$prefix has no SRCDIR in versions.env"

	mkdir -p "$BUILD_ROOT"
	rm -rf "${BUILD_ROOT:?}/$srcdir"
	tar -xf "$FETCHED" -C "$BUILD_ROOT"
	[ -d "$BUILD_ROOT/$srcdir" ] || die "expected $srcdir inside $(basename "$FETCHED")"
	SRC_PATH=$BUILD_ROOT/$srcdir
}
